spring:
  application:
    name: ${SPRING_APP_NAME:myApp}
  profiles:
    active: ${SPRING_ACTIVE_PROFILE:dev}

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/myapp}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root1234!@}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.MySQLDialect
    database: mysql

  cloud:
    aws:
      region:
        static: ${AWS_REGION}
      s3:
        bucket: ${AWS_S3_BUCKET}
